### AWS S3 Server ###
cloud:
  aws:
    credentials:
      accessKey: ENC(TzCmCwaesRqnHHirDgtAp+a+17FxJYHi+49DrT3Nmf0=)
      secretKey: ENC(Bjnp+6ENwYlEXvEJLlbtAVT7Ughmgqom4s0UrrIkSt6CECABfAvtlpCBRVDtHDisg2xSMZAr2iM=)
    s3:
      bucket: ENC(gZjR8l6H+2vxJXwOJ6yopNx/ppiY8SlWQpBXVcKkIrA=)
    region:
      static: ap-northeast-2
    stack:
      auto: false

### MariaDB Release Server ###
spring:
  datasource:
    url: ENC(8RGjgKwqoWxPXWWtozKImfcNo5GMUnCIMYvONc61FsNmKNqlVEmHnXVsHIEQBl9Ld7a/RJUCrSHzp7QxRKD0ldDBJju/8s6c)
    username: ENC(IYZiiPFZ/d7XM0OxII/y5ZjgTPU7eKRJ)
    password: ENC(tCx5PtshhUwYLTDIrXuItttIEB671nLL)

### KakaoMap Api Key ###
kakao:
  map:
    apiKey: ENC(r38lxxHEgR2UgVViu+F5a9H8kDhNnX3VXmYE+wdQGi1G6glVcckg1u1kQGknmAGutPwRGYc/o5c=)